### ISSUE TITLE
Hit Counter Badge isn't coming 

### ISSUE THREAD

**Issue by ghost** [brentvollebregt/hit-counter#26]
![IMG_20201127_194343](https://user-images.githubusercontent.com/54566209/100458041-1f905d00-30e9-11eb-9c8c-0f057e690148.jpg)

**The badge isn't coming up I don't know what is the problem even I can't see the badge in this repo also !**

**Comment by brentvollebregt** [comment]
Thanks for raising this, something had gone very wrong with the SQLite database - I have never seen this before:

```
2020-11-27 20:53:48,024: Exception on /count/tag.svg [GET]
Traceback (most recent call last):
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hitcounter/hit-counter/utils.py", line 51, in wrapper
    return func(url, *args, **kwargs)
  File "/home/hitcounter/hit-counter/server.py", line 80, in count_tag_route
    db_connection.add_view(connection, url)
  File "/home/hitcounter/hit-counter/db.py", line 45, in add_view
    count = self.get_count(connection, url)
  File "/home/hitcounter/hit-counter/db.py", line 34, in get_count
    cursor.execute('SELECT count FROM url WHERE url=?', (url,))
sqlite3.DatabaseError: database disk image is malformed
2020-11-27 20:54:23,254: Exception on / [GET]
Traceback (most recent call last):
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hitcounter/.virtualenvs/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hitcounter/hit-counter/server.py", line 52, in home_route
    top_domains=db_connection.get_top_sites(connection, config.NUM_TOP_DOMAINS),
  File "/home/hitcounter/hit-counter/db.py", line 54, in get_top_sites
    return self.__get_top(connection, amount, 'domains')
  File "/home/hitcounter/hit-counter/db.py", line 67, in __get_top
    [*[str(r) for r in config.TOP_SITES_IGNORE_DOMAIN_RE_MATCH], amount]
sqlite3.OperationalError: no such table: url
```

I have a backup script that keeps the last 5 days backed up. It seems something went wrong on the 25th so I have reverted back to the snapshot at 2020-11-25 03:03:19 UTC.

It looks like the demo server is back up now.

**Comment by ghost** [comment]
ok no problem it's back again, i wrote about this in your YouTube comments also
